services:
    api:
        container_name: engineermandi-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        env_file:
            - .env
