name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.22.0

            - name: Cache Go modules
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Install dependencies
              run: go mod download

            - name: Run tests
              run: go test -v ./...

            - name: Build the application
              run: go build -v -o ./bin/engineermandi-backend ./main.go

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: go-binaries
                  path: ./bin/engineermandi-backend

    docker:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Download build artifact
              uses: actions/download-artifact@v3
              with:
                  name: go-binaries

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GHCR_PAT }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/ankitnayan83/engineermandi-backend:latest
                      ghcr.io/ankitnayan83/engineermandi-backend:${{ github.sha }}

    deploy:
        runs-on: ubuntu-latest
        needs: docker

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install SSH client
              run: sudo apt-get install -y ssh

            - name: Deploy to production
              env:
                  EC2_HOST: ${{ secrets.EC2_HOST }}
                  EC2_USER: ${{ secrets.EC2_USER }}
                  EC2_SSH_KEY: ${{ secrets.EC2_KEY }}
                  DOCKER_IMAGE: ghcr.io/ankitnayan83/engineermandi-backend:latest
                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                  JWT_KEY: ${{ secrets.JWT_KEY }}
                  PORT: ${{ secrets.PORT }}
                  DB_URL: ${{ secrets.DB_URL }}
                  GHCR_PAT: ${{ secrets.GHCR_PAT }}
              run: |
                  echo "Deploying to production..."

                  # Set up SSH key
                  mkdir -p ~/.ssh
                  echo "$EC2_SSH_KEY" > ~/.ssh/ec2_key.pem
                  chmod 600 ~/.ssh/ec2_key.pem

                  # Add EC2 host to known hosts
                  ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

                  # Connect to EC2 and execute deployment commands
                  ssh -i ~/.ssh/ec2_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
                    # Create .env file on EC2
                    printf "GOOGLE_CLIENT_ID=%s\nGOOGLE_CLIENT_SECRET=%s\nJWT_KEY=%s\nPORT=%s\nDB_URL=%s\n" \
                      "$GOOGLE_CLIENT_ID" "$GOOGLE_CLIENT_SECRET" "$JWT_KEY" "$PORT" "$DB_URL" > .env

                    # Update the package index and install Docker if not present
                    sudo yum update -y
                    if ! command -v docker &> /dev/null; then
                        sudo amazon-linux-extras install docker -y
                        sudo systemctl start docker
                        sudo systemctl enable docker
                    fi

                    # Ensure Docker is running
                    sudo systemctl start docker

                    # Login to GitHub Container Registry
                    echo "${GHCR_PAT}" | sudo docker login ghcr.io -u ${EC2_USER} --password-stdin

                    # Stop and remove the old container if it exists
                    sudo docker stop engineermandi-backend || true
                    sudo docker rm engineermandi-backend || true

                    # Pull the latest Docker image
                    sudo docker pull ${DOCKER_IMAGE}

                    # Run the new container with the .env file
                    sudo docker run -d --env-file .env -p 80:80 --name engineermandi-backend ${DOCKER_IMAGE}
                  EOF
