name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.22.0

            - name: Cache Go modules
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Install dependencies
              run: go mod download

            - name: Run tests
              run: go test -v ./...

            - name: Build the application
              run: go build -v -o ./bin/engineermandi-backend ./main.go

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: go-binaries
                  path: ./bin/engineermandi-backend

    docker:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Download build artifact
              uses: actions/download-artifact@v3
              with:
                  name: go-binaries

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GHCR_PAT }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/ankitnayan83/engineermandi-backend:latest
                      ghcr.io/ankitnayan83/engineermandi-backend:${{ github.sha }}

    deploy:
        runs-on: ubuntu-latest
        needs: docker

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy to production
              env:
                  EC2_HOST: ${{ secrets.EC2_HOST }}
                  EC2_USER: ${{ secrets.EC2_USER }}
                  EC2_SSH_KEY: ${{ secrets.EC2_KEY }}
                  DOCKER_IMAGE: ghcr.io/ankitnayan83/engineermandi-backend:latest
                  GHCR_PAT: ${{ secrets.GHCR_PAT }}
                  JWT_KEY: ${{ secrets.JWT_KEY }}
                  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                  PORT: ${{ secrets.PORT }}
                  DB_URL: ${{ secrets.DB_URL }}
              run: |
                  echo "Deploying to production..."

                  sudo apt-get update
                  sudo apt-get install -y ssh

                  mkdir -p ~/.ssh

                  # Save private key to ec2_key.pem
                  echo "$EC2_SSH_KEY" > ec2_key.pem
                  chmod 600 ec2_key.pem

                  # Add the EC2 host key to known_hosts to avoid verification failures
                  ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

                  # SSH into EC2 and deploy
                  ssh -i ec2_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
                      set -e

                      # Ensure the target directory exists
                      mkdir -p /home/${EC2_USER}/env-files

                      # Write environment variables to .env file in the correct location
                      cat <<EOT > /home/${EC2_USER}/env-files/.env
                      JWT_KEY=${JWT_KEY}
                      GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
                      GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
                      PORT=${PORT}
                      DB_URL=${DB_URL}
                      EOT

                      # Update package index
                      sudo yum update -y

                      # Install Docker if not already installed
                      if ! command -v docker &> /dev/null
                      then
                          echo "Docker not found. Installing Docker..."
                          sudo amazon-linux-extras install docker -y
                          sudo systemctl start docker
                          sudo systemctl enable docker
                      fi

                      # Ensure Docker daemon is running
                      sudo systemctl start docker

                      # Login to Github Container Registry
                      echo "${GHCR_PAT}" | sudo docker login ghcr.io -u ${EC2_USER} --password-stdin

                      # Stop the old container if it exists
                      sudo docker stop engineermandi-backend || echo "Container not running, skipping stop."
                      sudo docker rm engineermandi-backend || echo "Container not found, skipping remove."

                      # Pull the latest image
                      sudo docker pull ${DOCKER_IMAGE}

                      # Run the new container with the .env file
                      sudo docker run --env-file /home/${EC2_USER}/env-files/.env -d -p 80:80 --name engineermandi-backend ${DOCKER_IMAGE}
                  EOF
